defaults: &defaults
  adapter: postgresql
  username: simranjit
  password: simran
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: mini_dev
  <<: *defaults

test:
  database: mini_test
  <<: *defaults

production:
  database: mini_production
  <<: *defaults